### PR TITLE
Basic support for recurring scheduled tasks

### PR DESCRIPTION
**Pull request by duckbytes**
Support for automatic daily recurring tasks.

Adds a view to see all the scheduled tasks set up. Add button is visible to admins.

image

An overview for making changes or disabling a scheduled task can be viewed by clicking on a card.

image

Adding a scheduled task view looks like this. Most components are similar to the guided setup components.

image

A lambda function runs each day at midnight. This adds the tasks to the system automatically and moves them to a PENDING status:

image

There is a notification badge at the top to show any unclaimed tasks in PENDING. You can accept or reject a job either by selecting them, using the context menu, or by opening the overview:

image

When you accept or reject a task you are assigned to it as a coordinator. Accepted tasks are moved to NEW and rejected moved to REJECTED with the time of rejection. You can also add a reason for rejection if you use selection mode, otherwise add it as a comment like usual.

Admins can add and change scheduled tasks. Coordinators can see pending tasks and accept or reject them.

This should work well enough for daily jobs like the air ambulance runs. More features are planned for this (https://github.com/platelet-app/platelet/discussions/149), but this will get us up and running.

@Joetooker95 @Merseybiker can you provide feedback please?

### CODE REVIEW

**Comment by Joetooker95** [comment]
This looks very good Theo.

**Comment by duckbytes** [comment]
Thanks Joe!

We'll have to take some care when we roll this out. Tasks will be created regardless of if the previous ones were claimed. If we know that someone isn't going to use the app for a particular shift, we'll either need to disable all the scheduled tasks the night before, or someone will need to go in each night and reject the created ones.

**Comment by Joetooker95** [comment]
Hi Theo,Let’s get it active and then I will keep on top of ensuring they are disabled at times it isn’t being used by coords, however I am now working through rolling it out to the rest of the charity and so I am hoping by the end of June we will be completely live.Only thing I really needed to check with you was the reports, do we still only have access to the last 2 weeks? This is something we will need to have full access to before going completely live as we will need to rely on it to get historic data.Kind regardsJoe TookerOn 18 May 2023, at 15:43, Theo ***@***.***> wrote:﻿
Thanks Joe!
We'll have to take some care when we roll this out. Tasks will be created regardless of if the previous ones were claimed. If we know that someone isn't going to use the app for a particular shift, we'll either need to disable all the scheduled tasks the night before, or someone will need to go in each night and reject the created ones.

**Comment by duckbytes** [comment]
I'll add some enable all and disable all buttons to the list view to make it a bit easier for you.

Sounds great about the plan to go live. I can look at reports now this is mostly finished. There are some other reasons I want to make the report view better, so probably a good time to improve it.

**Comment by Merseybiker** [comment]
Hi Theo and Joe.  The scheduled tasks enhancement looks great - some general comments and questions from MCBB:
1) We have some runs that are weekly but not every day - for instance one surgery pickup is every Tuesday and Thursday weekly.  Can it cope with that ?
2) When will the enhancement be pushed out to our Platelet production ?  I can't yet see it on the pilot environment...

**Comment by Merseybiker** [comment]
> > When will the enhancement be pushed out to our Platelet production ? I can't yet see it on the pilot environment...
> 
> I've been letting it run on my test instance for a few days and it seems to be working well, so I'll probably merge this to master later today. I could push it up to your instance at the same time if you'd like?

Yes please Theo....

**Pull request merged**
