### PR TITLE
Add sender and recipient name to picked up and delivered actions

### PR DESCRIPTION
**Pull request by duckbytes**
Allows the user to set the sender and recipient names when picked up and dropped off.

When clicking picked up action on the task overview:

image

Info icons appear next to the action, if a name has been set. Mousing over the icon gives a tooltip with the name, clicking the icon copies the name to clipboard.

image

Clicking the edit icon also lets you view and change the name, along with the time:

image

Setting multiple items as picked up:

image

@ianphunt58
@PaulFreewheelersEVS

Please let me know if this works for you.

### CODE REVIEW

**Comment by PaulFreewheelersEVS** [comment]
Hi Theo

 

Looks good but can you copy in John Cooper on these please.  Does he have a test instance?

 

Paul

 

From: Theo ***@***.***> 
Sent: 18 August 2022 13:37
To: platelet-app/platelet ***@***.***>
Cc: PaulFreewheelersEVS ***@***.***>; Mention ***@***.***>
Subject: [platelet-app/platelet] Add sender and recipient name to picked up and delivered actions (PR #84)

 

Allows the user to set the sender and recipient names when picked up and dropped off.

When clicking picked up action on the task overview:

 <https://user-images.githubusercontent.com/32309223/185394948-b7dfa045-21e9-4545-b460-6aa1a62dda92.png> 

Info icons appear next to the action, if a name has been set. Mousing over the icon gives a tooltip with the name, clicking the icon copies the name to clipboard.

 <https://user-images.githubusercontent.com/32309223/185395078-f9b9e168-5788-4233-9546-e310865c17e7.png> 

Clicking the edit icon also lets you view and change the name, along with the time:

 <https://user-images.githubusercontent.com/32309223/185395341-10029acc-5f48-4f98-804e-ea02b8660230.png> 

Setting multiple items as picked up:

 <https://user-images.githubusercontent.com/32309223/185395478-a6a1f204-fdc3-4bee-adb5-5b3231cdd6bc.png> 

@ianphunt58 <https://github.com/ianphunt58> 
@PaulFreewheelersEVS <https://github.com/PaulFreewheelersEVS> 

Please let me know if this works for you.

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/platelet-app/platelet/pull/84


Commit Summary


*	3395f2c <https://github.com/platelet-app/platelet/pull/84/commits/3395f2c5ed4bad703f8da203a2ab43e52dc34761>  task actions small refactor and unsubscribe test fix
*	79a6211 <https://github.com/platelet-app/platelet/pull/84/commits/79a621160245791c05ac95beef3dfc2d8270be6a>  timePickedUpSenderName and timeDroppedOffRecipientName fields on Task model
*	e47a3de <https://github.com/platelet-app/platelet/pull/84/commits/e47a3de476b3657ca6f904e3ec22dd47082467b2>  task actions name input for sender and recipient
*	a36e8ba <https://github.com/platelet-app/platelet/pull/84/commits/a36e8ba0431f7bc0f232dd8839453b4db26ace6f>  multiple selections name input for sender and recipient
*	0d89dd2 <https://github.com/platelet-app/platelet/pull/84/commits/0d89dd290048fec5b8b5eb1eb41978cb3d84196e>  info icons plus name tooltip
*	f1de3bb <https://github.com/platelet-app/platelet/pull/84/commits/f1de3bb68302144c72128715e0f0f0d3456975b8>  tooltip tests
*	b119d87 <https://github.com/platelet-app/platelet/pull/84/commits/b119d879a93316a7a4233eef57c945f5d2d65427>  Merge branch 'master' into time_names
*	a8f1f1e <https://github.com/platelet-app/platelet/pull/84/commits/a8f1f1e706953ab488ce851552e1ee80f5ee9e7b>  allow editing of pickup/dropoff names
*	e1adbc9 <https://github.com/platelet-app/platelet/pull/84/commits/e1adbc99f47389617dff85dc23a4db918781c9b5>  copy names to clipboard on info button press


File Changes 


(16 <https://github.com/platelet-app/platelet/pull/84/files>  files)

*	M amplify/backend/api/platelet/schema.graphql <https://github.com/platelet-app/platelet/pull/84/files#diff-cf740addb74bc2dba3642403b4c12f212f75e36e424b6c54cc578c1052298bb7>  (10) 
*	M src/graphql/mutations.js <https://github.com/platelet-app/platelet/pull/84/files#diff-891d78d606e3e98f2b08ba08860b2f8b2f13e9e9d8f7f6e17f6f2246e3c0e86c>  (46) 
*	M src/graphql/queries.js <https://github.com/platelet-app/platelet/pull/84/files#diff-d7319ddfce4c86abe760d4d0ebba6684c93d2a71a431b88472cc3c05c8f3047e>  (28) 
*	M src/graphql/subscriptions.js <https://github.com/platelet-app/platelet/pull/84/files#diff-0a7acf58f6e6130ee0b787b51ca1c7cfbeb4f0575a09e1f681aeccf1cfb58209>  (42) 
*	M src/models/index.d.ts <https://github.com/platelet-app/platelet/pull/84/files#diff-122dcc549a76aea5881fd20cb58311d1a36d2acede08716df548e743adb798ff>  (2) 
*	M src/models/schema.js <https://github.com/platelet-app/platelet/pull/84/files#diff-0836ab668708cde1dc05964e65f91ce4b7e7b7a97237e962fdd8759b8867a4c6>  (16) 
*	M src/scenes/Dashboard/components/MultipleSelectionActionsDialog.js <https://github.com/platelet-app/platelet/pull/84/files#diff-8a68e40a8c80cb7ef464c5bb50a5211fa50dae7e1d7f6684d535200cbbe948d2>  (35) 
*	M src/scenes/Dashboard/components/MultipleSelectionActionsMenu.js <https://github.com/platelet-app/platelet/pull/84/files#diff-9d3cce645fb6e39a3c58055597c3e25f5eadebc862744338c4f80d04ab1130c7>  (1) 
*	M src/scenes/Dashboard/components/MultipleSelectionActionsMenu.test.js <https://github.com/platelet-app/platelet/pull/84/files#diff-9718f1681493f0a5f86cf0761135291ffc40544e5e2348945d5576ea55ac26dd>  (192) 
*	M src/scenes/Dashboard/components/MultipleSelectionActionsSetTime.js <https://github.com/platelet-app/platelet/pull/84/files#diff-7387f4e641d75eb18374f48535fb6d22db34fb2cc7b345f7c42707d88ec38f58>  (4) 
*	M src/scenes/Dashboard/utilities/generateMultipleTaskTimeModels.js <https://github.com/platelet-app/platelet/pull/84/files#diff-408ca178e76f950894cf301a62b68e602827d4b8eef5f4c7725ef0c9d94bbe3a>  (20) 
*	M src/scenes/Task/components/TaskActionConfirmationDialogContents.js <https://github.com/platelet-app/platelet/pull/84/files#diff-5bf33ab3e524a64e10bbd541fd35f02a36c66a2b53cfeac29d2901e6d02959b0>  (135) 
*	M src/scenes/Task/components/TaskActions.js <https://github.com/platelet-app/platelet/pull/84/files#diff-daf19644ecbfb01000f1bc621e36ef02b5cd24da8417f5ce2c8f97b75da45c1a>  (171) 
*	M src/scenes/Task/components/TaskActions.test.js <https://github.com/platelet-app/platelet/pull/84/files#diff-935501f266dfe5798d9c1365fc291c708c675c4f8ac23481d98d5049af0673a3>  (276) 
*	A src/scenes/Task/components/TimeAndNamePicker.js <https://github.com/platelet-app/platelet/pull/84/files#diff-1e7b2ebee7c659a71bd9e9a5a9fafea1d2ef0956ac1ba6f1c876444211c653a2>  (194) 
*	M src/scenes/Task/components/TimePicker.js <https://github.com/platelet-app/platelet/pull/84/files#diff-8404cb5134a7c1d946dfc682568000c8e124f0cf9cc0106ed9eee36698fa737c>  (4) 


Patch Links:


*	https://github.com/platelet-app/platelet/pull/84.patch
*	https://github.com/platelet-app/platelet/pull/84.diff

**Comment by ianphunt58** [comment]
Good, thanks Theo. Understand it will not appear in my environment yet but it’s a key feature I needed

 

Ian

 

From: Theo ***@***.***> 
Sent: 18 August 2022 13:37
To: platelet-app/platelet ***@***.***>
Cc: ianphunt58 ***@***.***>; Mention ***@***.***>
Subject: [platelet-app/platelet] Add sender and recipient name to picked up and delivered actions (PR #84)

 

Allows the user to set the sender and recipient names when picked up and dropped off.

When clicking picked up action on the task overview:

 <https://user-images.githubusercontent.com/32309223/185394948-b7dfa045-21e9-4545-b460-6aa1a62dda92.png> 

Info icons appear next to the action, if a name has been set. Mousing over the icon gives a tooltip with the name, clicking the icon copies the name to clipboard.

 <https://user-images.githubusercontent.com/32309223/185395078-f9b9e168-5788-4233-9546-e310865c17e7.png> 

Clicking the edit icon also lets you view and change the name, along with the time:

 <https://user-images.githubusercontent.com/32309223/185395341-10029acc-5f48-4f98-804e-ea02b8660230.png> 

Setting multiple items as picked up:

 <https://user-images.githubusercontent.com/32309223/185395478-a6a1f204-fdc3-4bee-adb5-5b3231cdd6bc.png> 

@ianphunt58 <https://github.com/ianphunt58> 
@PaulFreewheelersEVS <https://github.com/PaulFreewheelersEVS> 

Please let me know if this works for you.

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/platelet-app/platelet/pull/84


Commit Summary


*	3395f2c <https://github.com/platelet-app/platelet/pull/84/commits/3395f2c5ed4bad703f8da203a2ab43e52dc34761>  task actions small refactor and unsubscribe test fix
*	79a6211 <https://github.com/platelet-app/platelet/pull/84/commits/79a621160245791c05ac95beef3dfc2d8270be6a>  timePickedUpSenderName and timeDroppedOffRecipientName fields on Task model
*	e47a3de <https://github.com/platelet-app/platelet/pull/84/commits/e47a3de476b3657ca6f904e3ec22dd47082467b2>  task actions name input for sender and recipient
*	a36e8ba <https://github.com/platelet-app/platelet/pull/84/commits/a36e8ba0431f7bc0f232dd8839453b4db26ace6f>  multiple selections name input for sender and recipient
*	0d89dd2 <https://github.com/platelet-app/platelet/pull/84/commits/0d89dd290048fec5b8b5eb1eb41978cb3d84196e>  info icons plus name tooltip
*	f1de3bb <https://github.com/platelet-app/platelet/pull/84/commits/f1de3bb68302144c72128715e0f0f0d3456975b8>  tooltip tests
*	b119d87 <https://github.com/platelet-app/platelet/pull/84/commits/b119d879a93316a7a4233eef57c945f5d2d65427>  Merge branch 'master' into time_names
*	a8f1f1e <https://github.com/platelet-app/platelet/pull/84/commits/a8f1f1e706953ab488ce851552e1ee80f5ee9e7b>  allow editing of pickup/dropoff names
*	e1adbc9 <https://github.com/platelet-app/platelet/pull/84/commits/e1adbc99f47389617dff85dc23a4db918781c9b5>  copy names to clipboard on info button press


File Changes 


(16 <https://github.com/platelet-app/platelet/pull/84/files>  files)

*	M amplify/backend/api/platelet/schema.graphql <https://github.com/platelet-app/platelet/pull/84/files#diff-cf740addb74bc2dba3642403b4c12f212f75e36e424b6c54cc578c1052298bb7>  (10) 
*	M src/graphql/mutations.js <https://github.com/platelet-app/platelet/pull/84/files#diff-891d78d606e3e98f2b08ba08860b2f8b2f13e9e9d8f7f6e17f6f2246e3c0e86c>  (46) 
*	M src/graphql/queries.js <https://github.com/platelet-app/platelet/pull/84/files#diff-d7319ddfce4c86abe760d4d0ebba6684c93d2a71a431b88472cc3c05c8f3047e>  (28) 
*	M src/graphql/subscriptions.js <https://github.com/platelet-app/platelet/pull/84/files#diff-0a7acf58f6e6130ee0b787b51ca1c7cfbeb4f0575a09e1f681aeccf1cfb58209>  (42) 
*	M src/models/index.d.ts <https://github.com/platelet-app/platelet/pull/84/files#diff-122dcc549a76aea5881fd20cb58311d1a36d2acede08716df548e743adb798ff>  (2) 
*	M src/models/schema.js <https://github.com/platelet-app/platelet/pull/84/files#diff-0836ab668708cde1dc05964e65f91ce4b7e7b7a97237e962fdd8759b8867a4c6>  (16) 
*	M src/scenes/Dashboard/components/MultipleSelectionActionsDialog.js <https://github.com/platelet-app/platelet/pull/84/files#diff-8a68e40a8c80cb7ef464c5bb50a5211fa50dae7e1d7f6684d535200cbbe948d2>  (35) 
*	M src/scenes/Dashboard/components/MultipleSelectionActionsMenu.js <https://github.com/platelet-app/platelet/pull/84/files#diff-9d3cce645fb6e39a3c58055597c3e25f5eadebc862744338c4f80d04ab1130c7>  (1) 
*	M src/scenes/Dashboard/components/MultipleSelectionActionsMenu.test.js <https://github.com/platelet-app/platelet/pull/84/files#diff-9718f1681493f0a5f86cf0761135291ffc40544e5e2348945d5576ea55ac26dd>  (192) 
*	M src/scenes/Dashboard/components/MultipleSelectionActionsSetTime.js <https://github.com/platelet-app/platelet/pull/84/files#diff-7387f4e641d75eb18374f48535fb6d22db34fb2cc7b345f7c42707d88ec38f58>  (4) 
*	M src/scenes/Dashboard/utilities/generateMultipleTaskTimeModels.js <https://github.com/platelet-app/platelet/pull/84/files#diff-408ca178e76f950894cf301a62b68e602827d4b8eef5f4c7725ef0c9d94bbe3a>  (20) 
*	M src/scenes/Task/components/TaskActionConfirmationDialogContents.js <https://github.com/platelet-app/platelet/pull/84/files#diff-5bf33ab3e524a64e10bbd541fd35f02a36c66a2b53cfeac29d2901e6d02959b0>  (135) 
*	M src/scenes/Task/components/TaskActions.js <https://github.com/platelet-app/platelet/pull/84/files#diff-daf19644ecbfb01000f1bc621e36ef02b5cd24da8417f5ce2c8f97b75da45c1a>  (171) 
*	M src/scenes/Task/components/TaskActions.test.js <https://github.com/platelet-app/platelet/pull/84/files#diff-935501f266dfe5798d9c1365fc291c708c675c4f8ac23481d98d5049af0673a3>  (276) 
*	A src/scenes/Task/components/TimeAndNamePicker.js <https://github.com/platelet-app/platelet/pull/84/files#diff-1e7b2ebee7c659a71bd9e9a5a9fafea1d2ef0956ac1ba6f1c876444211c653a2>  (194) 
*	M src/scenes/Task/components/TimePicker.js <https://github.com/platelet-app/platelet/pull/84/files#diff-8404cb5134a7c1d946dfc682568000c8e124f0cf9cc0106ed9eee36698fa737c>  (4) 


Patch Links:


*	https://github.com/platelet-app/platelet/pull/84.patch
*	https://github.com/platelet-app/platelet/pull/84.diff

**Comment by duckbytes** [comment]
@ianphunt58

Would you like me to merge these changes into your instance?

**Comment by ianphunt58** [comment]
Yes if its not too time consuming Theo, otherwise I will wait for future releases

 

Ian

**Comment by duckbytes** [comment]
No worries @ianphunt58, it should be updated now.

**Pull request merged**
