### PR TITLE
Added loading skeleton and filter search for locations, users, and vehicles list

### PR DESCRIPTION
**Pull request by LamVu1**
Issue [#32 ](https://github.com/platelet-app/platelet/issues/32)

### CODE REVIEW

**Comment by duckbytes** [comment]
Looks great, thank you.

What is the significance of the styling for md down on the root class? I can't see a difference when I remove it, except for the 100% width.

When changing colors it needs to be conscious of the current theme, e.g. something like `theme.palette.mode === "dark" ? "white" : "black"`

It does look fine without that extra styling though.

**Comment by LamVu1** [comment]
For the styling, I copied from TextFieldControlled used in TaskFilterTextfield component. Should I remove the styling?

**Comment by duckbytes** [comment]
Ahh yeah, I see.

I'd say remove the extra styling. Only keep the width part in root and display part in searchIcon. Are you happy to clean it up from TaskFilterTextfield too? I think it was left over from when I used the outlined textfield variant and a solid color on the appbar.

You can also clean up the filterUsers function in UsersList.js since it isn't being used any more.

Could we also display the model and manufacturer on the vehicle cards?

Another suggestion I have is to use useRef instead of useState for any data that doesn't influence what is rendered to the UI. Changes to a useRef value don't cause the component to rerender.

So for example in VehiclesList:

`const vehiclesRef = useRef([]); // instead of const [vehicles, setVehicles]`

in getVehicles:

`vehiclesRef.current = vehicles;`

and in onChangeFilterText:

`matchSorter(vehiclesRef.current, ... );`

This prevents the list from rendering more than it needs on first load.

**Comment by duckbytes** [comment]
Hey @LamVu1 is this ready to be merged?

**Comment by LamVu1** [comment]
@duckbytes Yes

**Comment by duckbytes** [comment]
Awesome, thank you.

**Pull request merged**
